name_normalization:
  옥탑지붕층:
    - 옥탑지붕층
    - 옥탑 지붕층
    - 옥탑지붕
    - 옥 탑 지붕 층
    - 옥 탑 지 봉 충
  지붕층:
    - 지붕층
    - 지붕 층
    - 지붕 충
    - 지 봉 충
  지붕층(태양광):
    - 지붕층 태양광
    - 지붕층(태양광)
    - 태양광 지붕
    - 태양광
    - 태 양 광
  옥상조경:
    - 옥상조경
    - 옥상 조경
    - 옥 상 조경
    - 옥 상 조 경
  업무시설:
    - 업무시설
    - 업무 시설
    - 업 무 시설
    - 업 무 시 설
  로비 및 홀:
    - 로비 및 홀
    - 로비및홀
    - 로비
    - 로비 및 을
    - 로비 RE
  화장실:
    - 화장실
    - 화 장 실
  기계식 주차장(지하1층):
    - 기계식 주차장
    - 기계식주차장
    - 기계식 주차
  저수조(지하1층):
    - 저수조
  소화수조 및 정화조(지하1층):
    - 소화수조 및 정화조
    - 소화수조 정화조
  기계실, 발전기실(지하1층):
    - 기계실, 발전기실
    - 기계실 및 발전기실
  제연팬룸(지하1층):
    - 제연팬룸
  주차통로 및 주차장(1F):
    - 주차통로 및 주차장
    - 주차통로
    - 주차장
    - 주 차 통 로
    - 주 차 장
  후정(1F):
    - 후정
    - 후 정

usage_order:
  - 옥탑지붕층
  - 지붕층
  - 지붕층(태양광)
  - 옥상조경
  - 업무시설
  - 로비 및 홀
  - 화장실
  - 주차통로 및 주차장(1F)
  - 후정(1F)
  - 저수조(지하1층)
  - 소화수조 및 정화조(지하1층)
  - 기계실, 발전기실(지하1층)
  - 제연팬룸(지하1층)
  - 기계식 주차장(지하1층)
