import json
from pathlib import Path

import pandas as pd


def write_mgtx_file(floor_load_types, mgtx_path: Path, encoding="cp949"):
    """
    MIDAS NX Import용 MGTX 파일 생성.
    업로드한 mgtx 파일 구조를 기준으로 FLOADTYPE 블록을 생성합니다.

    이번 버전에서는 재하 영역 절점 매핑을 생략하므로
    FLOORLOAD 블록은 생성하지 않습니다.
    """

    lines = []

    lines.append("; =========================================================")
    lines.append("; AUTO GENERATED BY PDF TO MIDAS FLOOR LOAD TYPE AUTOMATION")
    lines.append("; File type: MGTX")
    lines.append("; Encoding: CP949")
    lines.append("; Area node mapping is intentionally skipped.")
    lines.append("; This file creates Floor Load Types only.")
    lines.append("; =========================================================")
    lines.append("")

    lines.append("*FLOADTYPE    ; Define Floor Load Type")
    lines.append("; NAME, DESC                                           ; 1st line")
    lines.append("; LCNAME1, FLOAD1, bSBU1, ..., LCNAME8, FLOAD8, bSBU8  ; 2nd line")

    for item in floor_load_types:
        name = item["floor_load_type_name"]
        desc = make_desc(item)

        load_parts = []

        for load in item["loads"]:
            load_case = load["load_case"]
            value = format_number(load["value"])
            sbu = load["sbu"]

            load_parts.extend([load_case, value, sbu])

        lines.append(f"   {name}, {desc}")
        lines.append("   " + ", ".join(load_parts))

    lines.append("")
    lines.append("; ---------------------------------------------------------")
    lines.append("; FLOORLOAD block is not generated.")
    lines.append("; Assign Floor Loads shall be performed inside MIDAS NX.")
    lines.append("; ---------------------------------------------------------")
    lines.append("")
    lines.append("*ENDDATA")

    mgtx_path.write_text("\n".join(lines), encoding=encoding)


def make_desc(item):
    """
    Floor Load Type 설명문 생성.
    MIDAS 내부에서 원본 PDF 근거를 추적하기 위함입니다.
    """

    source_rows = item.get("source_rows", [])

    if not source_rows:
        return "PDF_AUTO"

    first = source_rows[0]

    source_pdf = first.get("source_pdf", "")
    source_page = first.get("source_page", "")

    review = ""

    for row in source_rows:
        if row.get("review_flag"):
            review = " REVIEW"
            break

    desc = f"PDF_AUTO {source_pdf} p{source_page}{review}"

    if len(desc) > 80:
        desc = desc[:80]

    return desc


def format_number(value):
    """
    MIDAS 입력용 숫자 형식 정리.
    -4.900000 같은 값을 -4.9로 정리합니다.
    """
    try:
        v = float(value)
        return f"{v:.6g}"
    except Exception:
        return str(value)


def write_log_files(classified_rows, floor_load_types, error_rows, output_dir: Path):
    """
    자동 생성 로그 저장.
    """
    output_dir.mkdir(exist_ok=True)

    log_xlsx = output_dir / "auto_input_log.xlsx"
    log_json = output_dir / "auto_input_log.json"
    error_txt = output_dir / "error_log.txt"

    pd.DataFrame(classified_rows).to_excel(log_xlsx, index=False)

    log_data = {
        "classified_rows": classified_rows,
        "floor_load_types": floor_load_types,
        "error_rows": error_rows
    }

    with open(log_json, "w", encoding="utf-8") as f:
        json.dump(log_data, f, ensure_ascii=False, indent=2)

    with open(error_txt, "w", encoding="utf-8") as f:
        for row in error_rows:
            f.write(str(row))
            f.write("\n")